---
x-airflow-common: &airflow-common
  image: apache/airflow:3.1.3
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY:-FBw013f9-6V7_5_8d_6S_9y1J1y_1i1A1o1z1J1s1n1M=}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Istanbul
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'True'
    AIRFLOW__WEBSERVER__SECRET_KEY: dev_key_123
  user: "50000:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: airflow standalone
    ports:
      - "8080:8080"
    volumes:
      - airflow-dags:/opt/airflow/dags
      - /home/train/onur_linux/week15/airflow3/logs:/opt/airflow/logs
    restart: always

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.2.3
    volumes:
      - airflow-dags:/tmp/git
    environment:
      - GIT_SYNC_REPO=https://github.com/onurikcu/dataops-week15.git
      - GIT_SYNC_BRANCH=main
      - GIT_SYNC_ROOT=/tmp/git
      - GIT_SYNC_DEST=repo
      - GIT_SYNC_WAIT=60
    restart: always

  rustfs:
    restart: always
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=dataops
      - RUSTFS_SECRET_KEY=Ankara06
      - RUSTFS_VOLUMES=/data
    volumes:
      - rustfs_data:/data

  spark_client:
    container_name: spark_client
    image: veribilimiokulu/pyspark:3.5.3_python-3.12_java17
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - spark:/dataops
    command: /bin/bash -c "apt update && apt install openssh-server sudo sshpass git -y && useradd -rm -d /home/ssh_train -s /bin/bash -g root -G sudo -u 1000 ssh_train && echo 'ssh_train:Ankara06' | chpasswd && service ssh start && tail -f /dev/null"

volumes:
  postgres-db-volume:
  rustfs_data:
  spark:
  airflow-dags: